#!/usr/bin/env node
// icons/*.svg + *.json  →  dist/ (the npm package) and preview/ (the README).
// Output is deterministic so CI can rebuild and fail on any difference.
import { mkdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, listIconNames, parseIcon, readCategories, readIcon, toCamel, toPascal, toSvgString, nodeToInner } from './lib.mjs';
import { validateAll } from './validate.mjs';
import { say, fail } from './log.mjs';

const ACCENT = '#a60ee5';
const DIST = join(ROOT, 'dist');
const PREVIEW = join(ROOT, 'preview');

export function loadIcons() {
  return listIconNames().map((name) => {
    const { svg, meta } = readIcon(name);
    return { name, node: parseIcon(svg).children, tags: meta.tags, categories: meta.categories, aliases: meta.aliases ?? [] };
  });
}

function write(path, content) {
  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, content);
}

function buildDist(icons) {
  rmSync(DIST, { recursive: true, force: true });
  for (const i of icons) write(join(DIST, 'svg', `${i.name}.svg`), toSvgString(i.node) + '\n');

  const symbols = icons.map((i) => `<symbol id="${i.name}" viewBox="0 0 24 24">${nodeToInner(i.node)}</symbol>`).join('\n');
  write(
    join(DIST, 'sprite.svg'),
    `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:none">\n${symbols}\n</svg>\n`,
  );

  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  write(
    join(DIST, 'icons.json'),
    JSON.stringify({ version: pkg.version, categories: readCategories(), icons: icons.map(({ name, tags, categories, aliases, node }) => ({ name, tags, categories, aliases, node })) }, null, 2) + '\n',
  );

  // ESM: named exports are icon nodes, so bundlers tree-shake unused icons.
  const lines = [
    '// Generated by scripts/build.mjs. Do not edit.',
    `export const version = ${JSON.stringify(pkg.version)};`,
    ...icons.map((i) => `export const ${toCamel(i.name)} = ${JSON.stringify(i.node)};`),
    `export const iconNodes = { ${icons.map((i) => `${JSON.stringify(i.name)}: ${toCamel(i.name)}`).join(', ')} };`,
    `export const aliases = ${JSON.stringify(Object.fromEntries(icons.flatMap((i) => i.aliases.map((a) => [a, i.name]))))};`,
    `export function toSvg(icon, { size = 24, color = 'currentColor', strokeWidth = 2, className } = {}) {`,
    `  const node = typeof icon === 'string' ? iconNodes[aliases[icon] ?? icon] : icon;`,
    `  if (!node) throw new Error('unknown icon: ' + icon);`,
    `  const esc = (v) => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');`,
    `  const inner = node.map(([tag, attrs]) => '<' + tag + ' ' + Object.entries(attrs).map(([k, v]) => k + '="' + esc(v) + '"').join(' ') + ' />').join('');`,
    `  return '<svg xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size + '" viewBox="0 0 24 24" fill="none" stroke="' + esc(color) + '" stroke-width="' + strokeWidth + '" stroke-linecap="round" stroke-linejoin="round"' + (className ? ' class="' + esc(className) + '"' : '') + '>' + inner + '</svg>';`,
    `}`,
    '',
  ];
  write(join(DIST, 'index.js'), lines.join('\n'));
  write(
    join(DIST, 'index.d.ts'),
    [
      '// Generated by scripts/build.mjs. Do not edit.',
      'export type IconNode = Array<[tag: string, attrs: Record<string, string>]>;',
      `export type IconName = ${icons.map((i) => JSON.stringify(i.name)).join(' | ')};`,
      'export declare const version: string;',
      ...icons.map((i) => `export declare const ${toCamel(i.name)}: IconNode;`),
      'export declare const iconNodes: Record<IconName, IconNode>;',
      'export declare const aliases: Record<string, IconName>;',
      'export declare function toSvg(icon: IconName | IconNode, options?: { size?: number | string; color?: string; strokeWidth?: number | string; className?: string }): string;',
      '',
    ].join('\n'),
  );

  // React: react is an optional peer, so the core package stays dependency-free.
  write(
    join(DIST, 'react.js'),
    [
      '// Generated by scripts/build.mjs. Do not edit.',
      "import { createElement, forwardRef } from 'react';",
      "import * as nodes from './index.js';",
      'const toProp = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());',
      'export function createIcon(displayName, node) {',
      "  const Icon = forwardRef(({ size = 24, color = 'currentColor', strokeWidth = 2, absoluteStrokeWidth = false, className, children, ...rest }, ref) =>",
      "    createElement('svg', { ref, xmlns: 'http://www.w3.org/2000/svg', width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: color,",
      '      strokeWidth: absoluteStrokeWidth ? (Number(strokeWidth) * 24) / Number(size) : strokeWidth,',
      "      strokeLinecap: 'round', strokeLinejoin: 'round', className: ['bl-icon', className].filter(Boolean).join(' '), 'aria-hidden': rest['aria-label'] ? undefined : true, ...rest },",
      '      ...node.map(([tag, attrs], i) => createElement(tag, { key: i, ...Object.fromEntries(Object.entries(attrs).map(([k, v]) => [toProp(k), v])) })), children));',
      '  Icon.displayName = displayName;',
      '  return Icon;',
      '}',
      ...icons.map((i) => `export const ${toPascal(i.name)} = createIcon(${JSON.stringify(toPascal(i.name))}, nodes.${toCamel(i.name)});`),
      '',
    ].join('\n'),
  );
  write(
    join(DIST, 'react.d.ts'),
    [
      '// Generated by scripts/build.mjs. Do not edit.',
      "import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from 'react';",
      "import type { IconNode } from './index.js';",
      "export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'ref'> { size?: number | string; color?: string; strokeWidth?: number | string; absoluteStrokeWidth?: boolean; }",
      'export type Icon = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;',
      'export declare function createIcon(displayName: string, node: IconNode): Icon;',
      ...icons.map((i) => `export declare const ${toPascal(i.name)}: Icon;`),
      '',
    ].join('\n'),
  );
}

/**
 * README previews. An <img> of a currentColor icon renders black on GitHub's
 * dark theme, so the sheets bake in colours and the README picks one with
 * <picture> and prefers-color-scheme.
 */
function sheet(icons, { fg, bg, muted }) {
  const cols = 8;
  const cw = 110;
  const ch = 96;
  const rows = Math.ceil(icons.length / cols);
  const w = cols * cw;
  const h = rows * ch + 8;
  const cells = icons
    .map((i, k) => {
      const x = (k % cols) * cw;
      const y = Math.floor(k / cols) * ch + 4;
      const label = i.name.length > 16 ? `${i.name.slice(0, 15)}…` : i.name;
      return (
        `<g transform="translate(${x + cw / 2 - 16} ${y + 14}) scale(1.3333)" fill="none" stroke="${fg}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${nodeToInner(i.node)}</g>` +
        `<text x="${x + cw / 2}" y="${y + 70}" text-anchor="middle" fill="${muted}" font-family="ui-monospace,SFMono-Regular,Menlo,monospace" font-size="10.5">${label}</text>`
      );
    })
    .join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">\n<rect width="${w}" height="${h}" rx="12" fill="${bg}"/>\n${cells}\n</svg>\n`;
}

function buildPreview(icons) {
  rmSync(PREVIEW, { recursive: true, force: true });
  write(join(PREVIEW, 'sheet-light.svg'), sheet(icons, { fg: '#1a1621', bg: '#ffffff', muted: '#6a6375' }));
  write(join(PREVIEW, 'sheet-dark.svg'), sheet(icons, { fg: '#ece8f3', bg: '#0d1117', muted: '#9a92a7' }));
  for (const i of icons) write(join(PREVIEW, 'accent', `${i.name}.svg`), toSvgString(i.node, { color: ACCENT }) + '\n');
}

/** Rewrite the generated block of the README so its count never drifts. */
function buildReadme(icons) {
  const path = join(ROOT, 'README.md');
  const readme = readFileSync(path, 'utf8');
  const cats = readCategories();
  const counts = Object.keys(cats)
    .map((c) => [c, icons.filter((i) => i.categories.includes(c)).length])
    .filter(([, n]) => n > 0)
    .map(([c, n]) => `${cats[c].title} ${n}`)
    .join(' · ');
  const block = [
    '<!-- icons:start (generated by npm run build) -->',
    `**${icons.length} icons** · ${counts}`,
    '',
    '<picture>',
    '  <source media="(prefers-color-scheme: dark)" srcset="preview/sheet-dark.svg" />',
    '  <source media="(prefers-color-scheme: light)" srcset="preview/sheet-light.svg" />',
    `  <img src="preview/sheet-light.svg" alt="All ${icons.length} Burtson Icons" width="100%" />`,
    '</picture>',
    '<!-- icons:end -->',
  ].join('\n');
  const next = readme.replace(/<!-- icons:start[\s\S]*?<!-- icons:end -->/, block);
  if (next !== readme) writeFileSync(path, next);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const failing = validateAll().filter((r) => r.errors.length);
  if (failing.length) {
    fail(`refusing to build: ${failing.length} icon(s) fail validation (npm run validate)`);
    process.exit(1);
  }
  const icons = loadIcons();
  buildDist(icons);
  buildPreview(icons);
  buildReadme(icons);
  say(`built ${icons.length} icons → dist/, preview/, README`);
}
