#!/usr/bin/env node
// @burtson-labs/icons/mui: every icon as an MUI SvgIcon, so MUI's own props
// (fontSize="small", color="primary", sx, inheritViewBox) work exactly as they
// do on @mui/icons-material. Swapping a Material icon for a Burtson one is an
// import change and nothing else. @mui/material is an optional peer.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { ROOT, toCamel, toPascal } from './lib.mjs';
import { say } from './log.mjs';
import { loadIcons } from './build.mjs';

const icons = loadIcons();
const js = [
  '// Generated by scripts/mui.mjs. Do not edit.',
  "import { createElement, forwardRef } from 'react';",
  "import * as SvgIconModule from '@mui/material/SvgIcon';",
  '// ESM gets the component as `default`; the CommonJS build (Node interop)',
  '// gets the module object there, with the component one level down.',
  'const SvgIcon = SvgIconModule.default?.default ?? SvgIconModule.default;',
  "import * as nodes from './index.js';",
  'const toProp = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());',
  '// SvgIcon paints `fill: currentColor` from CSS, which would flood outline',
  '// icons; sx puts it back to none after any caller sx.',
  'export function createMuiIcon(displayName, node) {',
  '  const Icon = forwardRef(function Icon({ sx, strokeWidth = 2, ...props }, ref) {',
  '    return createElement(',
  '      SvgIcon,',
  "      { ref, viewBox: '0 0 24 24', stroke: 'currentColor', strokeWidth, strokeLinecap: 'round', strokeLinejoin: 'round', ...props,",
  "        sx: [{ fill: 'none' }, ...(Array.isArray(sx) ? sx : sx ? [sx] : [])] },",
  '      ...node.map(([tag, attrs], i) => createElement(tag, { key: i, ...Object.fromEntries(Object.entries(attrs).map(([k, v]) => [toProp(k), v])) })),',
  '    );',
  '  });',
  '  Icon.displayName = displayName;',
  "  Icon.muiName = 'SvgIcon';",
  '  return Icon;',
  '}',
  ...icons.map(
    (i) =>
      `export const ${toPascal(i.name)} = /* @__PURE__ */ createMuiIcon(${JSON.stringify(toPascal(i.name))}, nodes.${toCamel(i.name)});`,
  ),
  '',
];
const dts = [
  '// Generated by scripts/mui.mjs. Do not edit.',
  "import type { SvgIconProps } from '@mui/material/SvgIcon';",
  "import type { ForwardRefExoticComponent, RefAttributes } from 'react';",
  "import type { IconNode } from './index.js';",
  'export type MuiIconProps = SvgIconProps & { strokeWidth?: number | string };',
  'export type MuiIcon = ForwardRefExoticComponent<MuiIconProps & RefAttributes<SVGSVGElement>> & { muiName: string };',
  'export declare function createMuiIcon(displayName: string, node: IconNode): MuiIcon;',
  ...icons.map((i) => `export declare const ${toPascal(i.name)}: MuiIcon;`),
  '',
];
writeFileSync(join(ROOT, 'dist', 'mui.js'), js.join('\n'));
writeFileSync(join(ROOT, 'dist', 'mui.d.ts'), dts.join('\n'));
say(`dist/mui.js: ${icons.length} MUI SvgIcon components`);
