#!/usr/bin/env node
// @burtson-labs/icons/mui: every icon as an MUI SvgIcon, so MUI's own props
// (fontSize="small", color="primary", sx, inheritViewBox, titleAccess) work
// exactly as they do on @mui/icons-material. Swapping a Material icon for a
// Burtson one is an import change and nothing else. @mui/material is an
// optional peer. Per-icon entries (`/mui/<name>`) mirror `/react/<name>`.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { ROOT, toCamel, toPascal } from './lib.mjs';
import { say } from './log.mjs';
import { loadIcons } from './build.mjs';

const icons = loadIcons();
const DIST = join(ROOT, 'dist');
mkdirSync(join(DIST, 'mui'), { recursive: true });

const FACTORY = [
  '// Generated by scripts/mui.mjs. Do not edit.',
  "import { createElement, forwardRef } from 'react';",
  "import * as SvgIconModule from '@mui/material/SvgIcon';",
  '// ESM gets the component as `default`; the CommonJS build (Node interop)',
  '// gets the module object there, with the component one level down.',
  'const SvgIcon = SvgIconModule.default?.default ?? SvgIconModule.default;',
  'const toProp = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());',
  '// SvgIcon paints `fill: currentColor` from CSS, which would flood outline',
  '// icons; sx puts it back to none after any caller sx. `title` is the /react',
  '// spelling of MUI\'s `titleAccess`: both label the icon and set role="img".',
  'export function createMuiIcon(displayName, node) {',
  '  const Icon = forwardRef(function Icon({ sx, strokeWidth = 2, title, titleAccess = title, ...props }, ref) {',
  '    return createElement(',
  '      SvgIcon,',
  "      { ref, viewBox: '0 0 24 24', stroke: 'currentColor', strokeWidth, strokeLinecap: 'round', strokeLinejoin: 'round', titleAccess, ...props,",
  "        sx: [{ fill: 'none' }, ...(Array.isArray(sx) ? sx : sx ? [sx] : [])] },",
  '      ...node.map(([tag, attrs], i) => createElement(tag, { key: i, ...Object.fromEntries(Object.entries(attrs).map(([k, v]) => [toProp(k), v])) })),',
  '    );',
  '  });',
  '  Icon.displayName = displayName;',
  "  Icon.muiName = 'SvgIcon';",
  '  return Icon;',
  '}',
  '',
].join('\n');
const FACTORY_DTS = [
  '// Generated by scripts/mui.mjs. Do not edit.',
  "import type { SvgIconProps } from '@mui/material/SvgIcon';",
  "import type { ForwardRefExoticComponent, RefAttributes } from 'react';",
  "import type { IconNode } from './types.js';",
  '/** MUI SvgIcon props plus the stroke width; `title` is an alias of `titleAccess`. */',
  'export type MuiIconProps = SvgIconProps & { strokeWidth?: number | string; title?: string };',
  'export type MuiIcon = ForwardRefExoticComponent<MuiIconProps & RefAttributes<SVGSVGElement>> & { muiName: string };',
  'export declare function createMuiIcon(displayName: string, node: IconNode): MuiIcon;',
  '',
].join('\n');
writeFileSync(join(DIST, 'mui-factory.js'), FACTORY);
writeFileSync(join(DIST, 'mui-factory.d.ts'), FACTORY_DTS);

// One module per icon, importing only its own node: tree-shaking by file.
for (const i of icons) {
  const p = toPascal(i.name);
  writeFileSync(
    join(DIST, 'mui', `${i.name}.js`),
    `import { createMuiIcon } from '../mui-factory.js';\nimport node from '../nodes/${i.name}.js';\nexport const ${p} = /* @__PURE__ */ createMuiIcon(${JSON.stringify(p)}, node);\nexport default ${p};\n`,
  );
  writeFileSync(
    join(DIST, 'mui', `${i.name}.d.ts`),
    `import type { MuiIcon } from '../mui-factory.js';\nexport declare const ${p}: MuiIcon;\nexport default ${p};\n`,
  );
}

// The barrel re-exports the per-icon modules, like dist/react.js does.
const js = [
  '// Generated by scripts/mui.mjs. Do not edit.',
  "export { createMuiIcon } from './mui-factory.js';",
  ...icons.map((i) => `export { ${toPascal(i.name)} } from './mui/${i.name}.js';`),
  '',
];
const dts = [
  '// Generated by scripts/mui.mjs. Do not edit.',
  "export { createMuiIcon } from './mui-factory.js';",
  "export type { MuiIcon, MuiIconProps } from './mui-factory.js';",
  ...icons.map((i) => `export { ${toPascal(i.name)} } from './mui/${i.name}.js';`),
  '',
];
writeFileSync(join(DIST, 'mui.js'), js.join('\n'));
writeFileSync(join(DIST, 'mui.d.ts'), dts.join('\n'));
// toCamel is still exported by lib for other scripts; keep the import explicit
// here so a future per-icon node import (nodes.<camel>) has it to hand.
void toCamel;
say(`dist/mui.js: ${icons.length} MUI SvgIcon components (+ dist/mui/<name>)`);
